[package]
name = "butane"
version = "0.1.0"
authors = ["James Oakley <james@electronstudio.org>"]
edition = "2018"

[features]
default = ["datetime", "uuid"]
sqlite = ["butane_core/sqlite"]
pg = ["butane_core/pg"]
datetime = ["butane_core/datetime", "butane_codegen/datetime"]
debug = ["butane_core/debug"]
tls = ["butane_core/tls"]
uuid = ["butane_core/uuid", "butane_codegen/uuid"]

[dependencies]
butane_codegen = { path = "../butane_codegen", version = "0.1.0" }
butane_core = { path = "../butane_core", version = "0.1.0" }


[dev-dependencies]
paste = "0.1"
chrono = { version = "0.4", features=["serde"] }
butane_core = { path = "../butane_core", version = "0.1.0" }
quote = "1.0"
proc-macro2="1.0"
uuid_for_test = {package="uuid", version = "0.8", features=["v4"] }
