[package]
name = "butane_cli"
version = "0.1.0"
authors = ["James Oakley <james@electronstudio.org>"]
edition = "2018"

[[bin]]
name = "butane"
path = "src/main.rs"

[dependencies]
failure = "0.1.5"
butane = { path="../butane", version="0.1" }
chrono = "0.4"
clap = "2.33"
quote = "1.0"
serde = "1.0"
serde_json = "1.0"