name: CI

on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Postgresql setup adapted from Diesel CI
      # Disable ssl as server doesn't have a trusted cert
    - name: Setup postgres
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql
        echo "host  all  postgres  127.0.0.1/32  trust" | sudo tee -a /etc/postgresql/13/main/pg_hba.conf
        sudo cat /etc/postgresql/13/main/pg_hba.conf
        sudo service postgresql restart && sleep 3
        echo BUTANE_PG_CONNSTR="host=localhost user=postgres sslmode=disable" >> $GITHUB_ENV
    - name: Build
      run: make build
    - name: Lint
      run: make lint
    - name: Test Core
      run: cd butane_core && cargo test --all-features
    - name: Test Codegen
      run: cd butane_codegen && cargo test --all-features
    - name: Test
      run: cd butane && cargo test --all-features
