[package]
name = "propane_cli"
version = "0.1.0"
authors = ["James Oakley <james@electronstudio.org>"]
edition = "2018"

[[bin]]
name = "propane"
path = "src/main.rs"

[dependencies]
failure = "0.1.5"
propane = { path="../propane", version="0.1" }
chrono = "0.4"
clap = "2.33"