[package]
name = "propane_core"
version = "0.1.0"
authors = ["James Oakley <james@electronstudio.org>"]
edition = "2018"

[features]
datetime = ["chrono"]

[dependencies]
bincode = "1.1"
failure = "0.1.5"
hex = "0.3"
lazycell = "1.2"
log = "0.4"
rusqlite = "0.18.0"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features=["serde"], optional = true }